services:
  - type: web
    name: news-aggregator-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/your-app.jar
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DATABASE_USERNAME
        value: ${DATABASE_USERNAME}
      - key: DATABASE_PASSWORD
        value: ${DATABASE_PASSWORD}